#if UNITY_EDITOR
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace CoinFlip.FlowFramework.Editor
{
    /// <summary>
    /// Regenerates <c>Flow.WhenAll.cs</c> (typed overloads 2–16) so the hand-written
    /// combinator file does not need manual maintenance.
    /// </summary>
    public static class FlowWhenAllGenerator
    {
        const string OutputPath = "Assets/Scripts/Flow/Flow.WhenAll.cs";

        [MenuItem("CoinFlip/Flow/Regenerate WhenAll (2–16)", priority = 50)]
        public static void Regenerate()
        {
            var sb = new StringBuilder(160_000);
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine();
            sb.AppendLine("namespace CoinFlip.FlowFramework");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Typed WhenAll overloads (2–16). Returns a Flow of ValueTuple results.");
            sb.AppendLine("    /// Optional <see cref=\"CancellationToken\"/> cancels the combined flow.");
            sb.AppendLine("    /// Regenerated by CoinFlip/Flow/Regenerate WhenAll — do not hand-edit.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public partial class Flow");
            sb.AppendLine("    {");

            for (var n = 2; n <= 16; n++)
            {
                AppendOverload(sb, n);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();

            File.WriteAllText(OutputPath, sb.ToString(), Encoding.UTF8);
            AssetDatabase.ImportAsset(OutputPath);
            Debug.Log($"Regenerated {OutputPath} (WhenAll 2–16).");
        }

        static void AppendOverload(StringBuilder sb, int n)
        {
            var types = new string[n];
            for (var i = 0; i < n; i++)
            {
                types[i] = "T" + (i + 1);
            }

            var typeParams = string.Join(", ", types);
            var tupleType = string.Join(", ", types);

            sb.Append("        public static Flow<(").Append(tupleType).Append(")> WhenAll<").Append(typeParams).AppendLine(">(");
            for (var i = 0; i < n; i++)
            {
                sb.Append("            Flow<").Append(types[i]).Append("> f").Append(i + 1).Append(',');
                sb.AppendLine();
            }

            sb.AppendLine("            CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.Append("            var parent = FlowPool.Rent<(").Append(tupleType).AppendLine(")>();");
            sb.AppendLine("            parent.AttachCancellation(cancellationToken);");
            sb.AppendLine("            if (parent.IsCompleted)");
            sb.AppendLine("            {");
            sb.AppendLine("                return parent;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.Append("            var remaining = ").Append(n).AppendLine(";");

            for (var i = 1; i <= n; i++)
            {
                sb.Append("            var a").Append(i).Append(" = f").Append(i)
                    .Append(" ?? Flow<T").Append(i).AppendLine(">.FromResult(default);");
                sb.Append("            T").Append(i).Append(" r").Append(i).AppendLine(" = default;");
            }

            sb.AppendLine();

            for (var i = 1; i <= n; i++)
            {
                sb.Append("            void Done").Append(i).AppendLine("()");
                sb.AppendLine("            {");
                sb.AppendLine("                if (parent.IsCompleted)");
                sb.AppendLine("                {");
                sb.AppendLine("                    return;");
                sb.AppendLine("                }");
                sb.AppendLine();
                sb.Append("                if (a").Append(i).AppendLine(".IsFaulted)");
                sb.AppendLine("                {");
                sb.AppendLine("                    try");
                sb.AppendLine("                    {");
                sb.Append("                        a").Append(i).AppendLine(".GetResult();");
                sb.AppendLine("                    }");
                sb.AppendLine("                    catch (Exception ex)");
                sb.AppendLine("                    {");
                sb.AppendLine("                        parent.TrySetException(ex);");
                sb.AppendLine("                    }");
                sb.AppendLine();
                sb.AppendLine("                    return;");
                sb.AppendLine("                }");
                sb.AppendLine();
                sb.Append("                if (a").Append(i).AppendLine(".IsCanceled)");
                sb.AppendLine("                {");
                sb.AppendLine("                    parent.TrySetCanceled();");
                sb.AppendLine("                    return;");
                sb.AppendLine("                }");
                sb.AppendLine();
                sb.Append("                r").Append(i).Append(" = a").Append(i).AppendLine(".GetResult();");
                sb.AppendLine("                if (System.Threading.Interlocked.Decrement(ref remaining) == 0)");
                sb.AppendLine("                {");
                sb.Append("                    parent.TrySetResult((");
                for (var j = 1; j <= n; j++)
                {
                    if (j > 1)
                    {
                        sb.Append(", ");
                    }

                    sb.Append('r').Append(j);
                }

                sb.AppendLine("));");
                sb.AppendLine("                }");
                sb.AppendLine("            }");
                sb.AppendLine();
            }

            for (var i = 1; i <= n; i++)
            {
                sb.Append("            a").Append(i).Append(".OnCompleted(Done").Append(i).AppendLine(");");
            }

            sb.AppendLine("            return parent;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }
    }
}
#endif
